// <auto-generated />
using ATM.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ATM.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20230709080905_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("ATM.Models.CassettesInfo", b =>
                {
                    b.Property<int>("Denomination")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountOfBanknotes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Denomination");

                    b.ToTable("Cassettes");
                });
#pragma warning restore 612, 618
        }
    }
}
